name: CI checks
on:
  pull_request:
    branches: [main]
jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: npm ci
      - name: Format with Prettier
        run: npx prettier --write .
      - name: Check code with ESlint
        run: npx eslint src --fix --ext .js,.jsx
