name: CI checks
on:
  pull_request:
    branches: [main]
jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: npm install
      - name: Format with Prettier
        run: npx prettier --write .